version: "3.9"

volumes:
  db-store:

services:
  ngrok:
    image: wernight/ngrok:latest
    container_name: ngrok
    ports:
      - 4040:4040
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: web:80
    depends_on:
      - web

  web:
    image: nginx:1.22.0-alpine
    container_name: web
    volumes:
      - ./src/docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/var/www/public
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build: ./src/docker/app
    container_name: app
    volumes:
      - ./src/:/var/www
    depends_on:
      - db

  db:
    build: ./src/docker/db
    container_name: db
    volumes:
      - ./src/docker/db/initdb.d:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
